spring.application.name=ApiChallenge
spring.datasource.url=jdbc:mysql://localhost:3306/apicoding
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
JWT_KEY=VGhpc0lzQVN1cGVyU2VjdXJlS2V5Rm9ySldUMjU2Qml0cw==
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss.SSS

